import { ReactNode } from "react";

import { TLayoutTypes } from "@/@core/types/layout.type";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutTypes = { children: ReactNode } & TLayoutTypes;

export default function LocaleLayout({
  children,
  params: { locale },
}: RootLayoutTypes) {
  return (
    <html lang={locale} suppressHydrationWarning={true}>
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
