import { ReactNode } from "react";

import { TLayoutTypes } from "@/@core/types/layout.type";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { cookies } from "next/headers";

import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutTypes = { children: ReactNode } & TLayoutTypes;

export default function LocaleLayout({
  children,
  params: { locale },
}: RootLayoutTypes) {
  // ** Cookie
  const cookieStore = cookies();

  // ** Theme
  const theme = cookieStore.get("theme");

  return (
    <html
      lang={locale}
      suppressHydrationWarning={true}
      data-theme={theme?.value || "light"}
    >
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
